Update style, searchbar, and dropdown
EssentialGG/Vigilance pull request #53
Opened 2022-06-22 23:38 UTC by BlackBeltPanda

Update SettingsGui to new style and add new colors to VigilancePalette and VigilanceConfig
Deprecate old DropDown and replace with new DropDownComponent
Replace searchbar in SettingsTitle

2022-07-04 12:53 UTC, Johni0702 requested changes

2022-07-04 12:53 UTC, Johni0702 commented on src/main/kotlin/gg/essential/vigilance/gui/settings/DropDownComponent.kt
> +    private val optionContainerHeight = 18
This is different from what we are using in Essential (20). Why is that? If it's intentional, then should we maybe allow it to be configured via a constructor parameter?

2022-07-05 10:57 UTC, Johni0702 requested changes

2022-07-05 10:57 UTC, Johni0702 commented on src/main/kotlin/gg/essential/vigilance/gui/SettingsCategory.kt
> +        scroller.addScrollAdjustEvent(true) { _, _ ->
I guess practically it doesn't make a difference cause the ScrollComponent invokes both all the time, but logically it should be `isHorizontal = false`, no?

2022-07-05 10:57 UTC, Johni0702 commented on src/main/kotlin/gg/essential/vigilance/gui/SettingsCategory.kt
> +        scroller.onMouseScroll {
You reverted this again. Why?

2022-07-05 10:57 UTC, Johni0702 commented on src/main/kotlin/gg/essential/vigilance/gui/settings/DropDownComponent.kt
>          x = 2.pixels(alignOpposite = true)
Another case of padding that's now handled by `scrollerContainer`.
```suggestion
        x = 0.pixels(alignOpposite = true)
```

2022-07-06 11:17 UTC, Johni0702 approved these changes

2022-07-06 15:48 UTC, BlackBeltPanda commented
Need to add one or two more things before merging this in.

2022-07-11 09:05 UTC, Johni0702 requested changes

2022-07-11 09:05 UTC, Johni0702 commented on src/main/kotlin/gg/essential/vigilance/gui/SettingsGui.kt
> +                        UKeyboard.KEY_RIGHT -> if (child.component.enabled) child.component.click()
Now that the black part is the knob, this needs to be swapped again.

2022-07-12 09:53 UTC, Johni0702 approved these changes

2022-07-12 09:54 UTC, merged